# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `bank_project`")
spark.sql("USE SCHEMA `bank_project`")

# COMMAND ----------

display(spark.sql("SELECT * FROM bank_project.bank_project.silver_customers_transformed_scd1").orderBy("customer_id"))

# COMMAND ----------

display(spark.sql("SELECT * FROM bank_project.bank_project.silver_accounts_transactions_transformed_scd2 WHERE account_id = 100010"))
